########################################################################
#MOVIMENTO_STANDARD_TERMINAL:
TMOV:
########################################################################
 initial_handling: I_DISCHARGE,I_TRANSFER
 I_DISCHARGE:
  label: Discharge From Ship
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   container_in_terminal: false
   handling_header_status: NEW
  set:
   container_in_terminal: true
   container_FE_copy: true
   operation_type: 'MT'
   seal_imp_copy: true
 O_EMPTYING:
  label: Out for Emptying
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   container_in_terminal: true
   container_FE: F
#   container_status: AVAILABLE
  set:  
   container_in_terminal: false
   operation_type: 'MT'
 I_EMPTYING:
  label: In after Emptying
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   container_in_terminal: false
   container_FE: F
  set:
   container_in_terminal: true
   container_FE_copy: false
   operation_type: 'MT'
 O_FILLING:
  label: Out for Filling
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   with_booking: false
   container_in_terminal: true
   container_FE: E
#   container_status: AVAILABLE
  set:  
   container_in_terminal: false
   booking_copy: true
   operation_type: 'MT'
 I_FILLING:
  label: 'In From Filling'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   container_FE: E
  set:
   container_in_terminal: true
   container_FE_copy: true
   operation_type: 'MT'
 I_TRANSFER:
  label: 'In By Transfer From Other Terminal'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   handling_header_status: NEW
  set:
   container_in_terminal: true
   container_FE_copy: true
   operation_type: 'MT'
 O_LOAD:
  label: Out For Load
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'
  check:
   container_in_terminal: true
  set:
   container_in_terminal: false
   container_FE_copy: true
   movimento_status: CLOSE
   operation_type: 'MT'
 REQ_ESTIMATE:
  label: Estimate Request
  icon: '<i class="fa fa-fax fa-2x" style="color:white;"></i>'
  check:
   container_in_terminal: true
  set:
   container_status: DAMAGED
   operation_type: 'RE'
 CUST_INSP:
  icon: '<i class="fa fa-tasks fa-2x" style="color:white;"></i>' 
  label: Custom Inspections
  check:
   container_in_terminal: true
  set:
   operation_type: 'CI'

########################################################################
#HANDLING_ONLY_FRIDGE_CONNECTION:
FRCON:
########################################################################
 initial_handling: IN_FRO_FRIDGE_CONNECTION
 IN_FRO_FRIDGE_CONNECTION:
  set:
   container_in_terminal: true
 OUT_FRO_FRIDGE_CONNECTION:
  check:
   is_container_frigo: true
   container_in_terminal: false
  set:
   handling_status: CLOSE

########################################################################
#HANDLING_ONLY_CUSTOMS_INSPECTION:
INSPE:
########################################################################
 initial_handling: CUSTOMS_INPSECTION
 CUSTOMS_INPSECTION:
  set:
   handling_status: CLOSE
  
  