########################################################################
#MOVIMENTO_STANDARD_TERMINAL:
TMOV:
########################################################################
 initial_handling: I_DISCHARGE,I_TRANSFER,I_EMPTYING
 I_DISCHARGE:
  label: Discharge From Ship
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   container_in_terminal: false
   handling_header_status: NEW
  set:
   container_in_terminal: true
   container_FE_copy: true
   operation_type: 'MT'
   seal_imp_copy: true
   start_reefer_connection: IF_FULL
   lock_INSPECT: IF_EMPTY
   handling_header_status_by_config:
    :new_status: CLOSE
    :shipowner_id: 3,5,16,7,14,10,11,12,13,15,19,20
    :reefer: false
    :container_FE: F   
 O_EMPTYING:
  label: Out for Emptying
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   with_booking: false  
   container_in_terminal: true
   container_FE: F
  set:  
   container_in_terminal: false
   operation_type: 'MT'
   end_reefer_connection: true
 I_EMPTYING:
  label: In after Emptying
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   with_booking: false  
   container_in_terminal: false
   container_FE: F
  set:
   container_in_terminal: true
   container_FE_copy: false
   operation_type: 'MT'
   lock_INSPECT: IF_EMPTY
 O_FILLING:
  label: Out for Filling
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   with_booking: false
   container_in_terminal: true
   container_FE: E
  set:  
   container_in_terminal: false
   booking_copy: true
   operation_type: 'MT'
   end_reefer_connection: true
   handling_header_status_by_config:
    :new_status: CLOSE
    :shipowner_id: 3
    :reefer: false
 O_RETURN:
  label: Out for Return
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'
  check:
   with_booking: true
   container_in_terminal: true
   container_FE: F
  set:
   container_in_terminal: false
   booking_copy: true
   operation_type: 'MT'
   end_reefer_connection: true   
 I_FILLING:
  label: 'In From Filling'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   container_FE: E
  set:
   container_in_terminal: true
   container_FE_copy: true
   seal_exp_copy: true   
   operation_type: 'MT'
   lock_INSPECT: IF_EMPTY
   start_reefer_connection: IF_FULL
   save_in_hi_weight_exp: true
   to_weigh: true
 I_RETURN:
  label: 'In From Return'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   with_booking: true  
   container_in_terminal: false
   container_FE: F
  set:
   container_in_terminal: true
   container_FE_copy: true
   seal_exp_copy: true
   operation_type: 'MT'
   lock_INSPECT: IF_EMPTY
   start_reefer_connection: IF_FULL   
 I_TRANSFER:
  label: 'In By Transfer From Other Terminal'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   handling_header_status: NEW
  set:
   seal_imp_copy: true  
   container_in_terminal: true
   container_FE_copy: true
   operation_type: 'MT'
   lock_INSPECT: IF_EMPTY
   start_reefer_connection: IF_FULL
   to_weigh: IF_FULL         
 O_LOAD:
  label: Out For Load
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'
  check:
   container_in_terminal: true
  set:
   container_in_terminal: false
   container_FE_copy: true
   handling_header_status: CLOSE
   booking_copy: true
   operation_type: 'MT'
   end_reefer_connection: true   
 I_NOT_POSIT:
  label: In for missing positioning
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   container_in_terminal: false
   container_FE: E
  set:
   container_in_terminal: true
   container_FE_copy: false
   operation_type: 'MT'
   booking_reset: true
   lock_INSPECT: IF_EMPTY
   start_reefer_connection: IF_FULL      
 I_REUSE:
  label: In for reuse
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   with_booking: false
   container_in_terminal: false
   container_FE: F
  set:
   container_in_terminal: true
   booking_copy: true
   operation_type: 'MT'
   lock_INSPECT: IF_EMPTY
   start_reefer_connection: IF_FULL      
 REQ_ESTIMATE:
  label: Estimate Request
  icon: '<i class="fa fa-fax fa-2x" style="color:white;"></i>'
  check:
   container_in_terminal: true
  set:
   container_status: DAMAGED
   operation_type: 'RE'
 CUST_INSPECTION:
  icon: '<i class="fa fa-tasks fa-2x" style="color:white;"></i>' 
  label: Custom Inspections
  check:
   container_in_terminal: true
  set:
   operation_type: 'CI'
 LOCK:
  label: Lock handling
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'
  check:
  set:
 UNLOCK:
  label: Unlock handling
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   lock_type: LOCK
  set:
   clear_lock: true
 INSPECT:
  label: Inspect
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   lock_type: INSPECT
  set:
   clear_lock: true
# DAMAGED_AU:
#  label: Authorized
#  icon: '<i class="fa fa-warning fa-2x" style="color:green;"></i>'
#  check:
#   lock_type: DAMAGED
#  set:         
 REPAIR:
  label: Repair
  icon: '<i class="fa fa-thumbs-o-up fa-2x" style="color:green;"></i>'
  hide_for_select: Y
  check:
   lock_type: DAMAGED
  set:
   clear_lock: true   


########################################################################
#HANDLING_ONLY_FRIDGE_CONNECTION:
FRCON:
########################################################################
 initial_handling: START_RFCON
 START_RFCON:
  icon: '<i class="fa fa-bolt fa-2x" style="color:white;"></i>'
  label: Connect Frigo
  check:
#   is_container_frigo: true
   handling_header_status: NEW
  set:
   start_reefer_connection: true
   container_in_terminal: true
 END_RFCON:
  icon: '<i class="fa fa-bolt fa-2x" style="color:white;"></i>'
  label: Disconnect Frigo
  set:
   end_reefer_connection: true
   handling_header_status: CLOSE
 CUST_INSPECTION:
  icon: '<i class="fa fa-tasks fa-2x" style="color:white;"></i>' 
  label: Custom Inspections
  check:
   container_in_terminal: true
  set:
   operation_type: 'CI'


########################################################################
#HANDLING_ONLY_CUSTOMS_INSPECTION:
INSPE:
########################################################################
 initial_handling: CUST_INSPECTION
 CUST_INSPECTION:
  icon: '<i class="fa fa-tasks fa-2x" style="color:white;"></i>' 
  label: Custom Inspections 
  set:
   operation_type: 'CI'  
   handling_header_status: CLOSE
  
  