########################################################################
#MOVIMENTO_STANDARD_TERMINAL:
TMOV:
########################################################################
 initial_handling: I_DISCHARGE,I_TRANSFER
 ASS_BOOK:
  label: Assign booking
  icon: '<i class="fa fa-ticket fa-2x" style="color:white;"></i>'
  check:
   with_booking: false   
#   container_status: AVAILABLE
  set:
   booking_copy: true
   with_booking: true
 I_DISCHARGE:
  label: Discharge From Ship
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>'
  check:
   container_in_terminal: false
   handling_header_status: NEW
  set:
   container_in_terminal: true
   container_FE_copy: true
 O_DISCHARGE:
  label: Out for Discharge
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   container_in_terminal: true
   container_FE: F
#   container_status: AVAILABLE
  set:  
   container_in_terminal: false   
 O_LOAD:
  label: Out for Load
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>' 
  check:
   with_booking: true  
   container_in_terminal: true
   container_FE: E
#   container_status: AVAILABLE
  set:  
   container_in_terminal: false
 REQ_ESTIMATE:
  label: Estimate Request
  icon: '<i class="fa fa-fax fa-2x" style="color:white;"></i>'   
  check:
   container_in_terminal: true
  set:
   container_status: DAMAGED
 I_LOAD:
  label: 'In From Load'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   container_FE: E
  set:
   container_in_terminal: true
   container_FE_copy: true
 I_DISCHARGE:
  label: 'Input From Discharge'
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   container_FE: F
  set:
   container_in_terminal: true
   container_FE_copy: true
 O_LOAD:
  label: Out For Load
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'
  check:
   with_booking: true  
   container_in_terminal: true
   container_FE: F
  set:
   container_in_terminal: false
   movimento_status: CLOSE
 CUST_INSP:
  icon: '<i class="fa fa-tasks fa-2x" style="color:white;"></i>' 
  label: Custom Inspections
  check:
   container_in_terminal: true
 O_REPAIR:
  label: Out For Repair
  icon: '<i class="fa fa-upload fa-2x" style="color:red;"></i>'   
  check:
   container_in_terminal: true
  set:
   container_in_terminal: false
 I_REPAIR:
  label: In From Repair
  icon: '<i class="fa fa-download fa-2x" style="color:green;"></i>' 
  check:
   container_in_terminal: false
   container_status: DAMAGED
  set:
   container_in_terminal: true
   container_status: AVAILABLE

########################################################################
HANDLING_ONLY_FRIDGE_CONNECTION:
########################################################################
 initial_handling: IN_FRO_FRIDGE_CONNECTION
 IN_FRO_FRIDGE_CONNECTION:
  set:
   container_in_terminal: true
 OUT_FRO_FRIDGE_CONNECTION:
  check:
   is_container_frigo: true
   container_in_terminal: false
  set:
   handling_status: CLOSE

########################################################################
HANDLING_ONLY_CUSTOMS_INSPECTION:
########################################################################
 initial_handling: CUSTOMS_INPSECTION
 CUSTOMS_INPSECTION:
  set:
   handling_status: CLOSE
  
  